version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    environment:
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_CERT_FILE=/etc/grafana/ssl/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/ssl/grafana.key
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_DOMAIN=jubilee.homingbeacon.net
      - GF_SERVER_ROOT_URL=https://jubilee.homingbeacon.net:13000
      - GF_SERVER_ENFORCE_DOMAIN=False
      - GF_PLUGIN_MARCUSOLSSON_CSV_DATASOURCE_ALLOW_LOCAL_MODE=True
      - GF_USERS_DEFAULT_THEME=light
    restart: unless-stopped
    ports:
      - '13000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./conf/grafana.db:/var/lib/grafana/grafana.db
      - ./conf/plugins:/var/lib/grafana/plugins
      - ./conf/ssl:/etc/grafana/ssl
      - ./conf/img:/usr/share/grafana/public/img
volumes:
    grafana-storage: {}
